"""add_shortcuts_table

Revision ID: 0df5c058911f
Revises: c3d4e5f6g7h8
Create Date: 2026-01-23 18:12:18.181211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df5c058911f'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortcuts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio_message_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=50), nullable=False),
    sa.Column('custom_icon', sa.String(length=10), nullable=True),
    sa.Column('custom_color', sa.String(length=7), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position IS NULL OR (position >= 1 AND position <= 6)', name='position_range'),
    sa.ForeignKeyConstraint(['audio_message_id'], ['audio_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortcuts')
    # ### end Alembic commands ###
