"""add ai_instructions to category

Revision ID: 7b84a3a6206c
Revises: f4f0fddb61a4
Create Date: 2025-12-21 21:41:08.061000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b84a3a6206c'
down_revision = 'f4f0fddb61a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('ai_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'ai_instructions')
    # ### end Alembic commands ###
